statement: Present perfect (has/have + VP) is permitted only in conditional antecedents and relative clauses. Use present tense for current state assertions.
trigger: Structural rule from spec document
related: []
tags:
  - tense
  - conditional
  - grammar
created: 2026-02-05
